### ISSUE TITLE
Oleg's to do list

### ISSUE THREAD

**Issue by phadej** [haskell-strict/strict#4]
- [x] `Strict` type-class #3
- [x] Add flagged dependency on `assoc` (instances for Pair and Either) #6 
- [x] Add changelog #5 
- [x] Add strict `These` #9 
- [x] `src/` directory
- [x] Safe Haskell #7 
- [ ] Eq1/Ord1/Show1/Read1/Hashable1/NFData1 instances #11

**Comment by infinity0** [comment]
There is also https://hackage.haskell.org/package/smash similar to `these`.

However at some point it does raise the question of where do we stop - for data/state-like types it is good to have all fields strict, but for control-like types sometimes you want just some of the fields to be strict.

**Comment by phadej** [comment]
`smash` is an experiment, `these` is actually used out there.
